export const LOAD_USERS = "LOAD_USERS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USER_BY_ID = "LOAD_USER_BY_ID";
export const LOAD_USER_BY_ID_SUCCESS = "LOAD_USER_BY_ID_SUCCESS";
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
